REVOKE ALL PRIVILEGES ON TABLE public.service_history_customers FROM anon;
REVOKE ALL PRIVILEGES ON TABLE public.service_history_bills FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.service_history_customers TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.service_history_bills TO authenticated;
DROP POLICY IF EXISTS "Public users can browse service history customers" ON public.service_history_customers;
DROP POLICY IF EXISTS "Public users can add service history customers" ON public.service_history_customers;
DROP POLICY IF EXISTS "Public users can update service history customers" ON public.service_history_customers;
DROP POLICY IF EXISTS "Public users can delete service history customers" ON public.service_history_customers;
DROP POLICY IF EXISTS "Public users can browse service history bills" ON public.service_history_bills;
DROP POLICY IF EXISTS "Public users can add service history bills" ON public.service_history_bills;
DROP POLICY IF EXISTS "Public users can update service history bills" ON public.service_history_bills;
DROP POLICY IF EXISTS "Public users can delete service history bills" ON public.service_history_bills;
CREATE POLICY "Signed-in shop users can browse service history customers" ON public.service_history_customers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Signed-in shop users can add service history customers" ON public.service_history_customers FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Signed-in shop users can update service history customers" ON public.service_history_customers FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Signed-in shop users can delete service history customers" ON public.service_history_customers FOR DELETE TO authenticated USING (true);
CREATE POLICY "Signed-in shop users can browse service history bills" ON public.service_history_bills FOR SELECT TO authenticated USING (true);
CREATE POLICY "Signed-in shop users can add service history bills" ON public.service_history_bills FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Signed-in shop users can update service history bills" ON public.service_history_bills FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Signed-in shop users can delete service history bills" ON public.service_history_bills FOR DELETE TO authenticated USING (true);
DROP POLICY IF EXISTS "Public users can view service bill files" ON storage.objects;
DROP POLICY IF EXISTS "Public users can upload service bill files" ON storage.objects;
DROP POLICY IF EXISTS "Public users can update service bill files" ON storage.objects;
DROP POLICY IF EXISTS "Public users can delete service bill files" ON storage.objects;
CREATE POLICY "Signed-in shop users can view service bill files" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = 'service-bills');
CREATE POLICY "Signed-in shop users can upload service bill files" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'service-bills' AND lower((storage.foldername(name))[1]) = 'service-bills');
CREATE POLICY "Signed-in shop users can update service bill files" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'service-bills') WITH CHECK (bucket_id = 'service-bills');
CREATE POLICY "Signed-in shop users can delete service bill files" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'service-bills');